In [1]:
from PIL import Image
import numpy as np


image = Image.open("example_pic.jpg")

In [2]:
# image_flattened = image.get_flattened_data()
# w = image.width
# h = image.height

# image_mat = np.array(image_flattened).reshape(176, 176)
# print(image_mat)

image_mat = np.array(image)
print(image_mat[80, :])
print(image_mat.dtype)

[[ 55  90 130]
 [ 55  90 130]
 [ 55  90 130]
 ...
 [ 18  41  93]
 [ 18  41  93]
 [ 18  41  93]]
uint8


In [3]:
import torch

image_tensor = torch.tensor(image_mat)
print(image_tensor)

tensor([[[ 37,  76, 119],
         [ 37,  76, 119],
         [ 38,  77, 120],
         ...,
         [ 14,  37,  89],
         [ 13,  36,  88],
         [ 12,  35,  87]],

        [[ 36,  75, 118],
         [ 37,  76, 119],
         [ 37,  76, 119],
         ...,
         [ 14,  37,  89],
         [ 13,  36,  88],
         [ 12,  35,  87]],

        [[ 35,  74, 117],
         [ 36,  75, 118],
         [ 37,  76, 119],
         ...,
         [ 15,  38,  90],
         [ 14,  37,  89],
         [ 13,  36,  88]],

        ...,

        [[143, 131,  81],
         [147, 135,  83],
         [153, 142,  88],
         ...,
         [ 72,  61,   0],
         [ 71,  60,   0],
         [ 70,  59,   0]],

        [[143, 132,  76],
         [146, 136,  77],
         [151, 141,  82],
         ...,
         [ 75,  64,   0],
         [ 77,  63,   0],
         [ 76,  62,   0]],

        [[145, 135,  74],
         [146, 136,  75],
         [148, 138,  76],
         ...,
         [ 75,  64,   0],
        

In [4]:
image_tensor_f32 = image_tensor.to(torch.float32)

In [14]:
# def compute_avg_channel(channel: int, tensor):
#     return sum(image_tensor_f32[:, :, channel]) / (image_tensor_f32.shape[0] * image_tensor_f32.shape[1])

def compute_avg_channel(tensor: torch.Tensor):
    return tensor.mean((0, 1), keepdim=True)

def compute_std_channel(tensor: torch.Tensor):
    return tensor.std((0, 1), keepdim=True)

In [15]:
avg_channels = compute_avg_channel(image_tensor_f32)
print(avg_channels)

std_channels = compute_std_channel(image_tensor_f32)
print(std_channels)

tensor([[[138.3976, 153.5532, 158.3934]]])
tensor([[[68.4510, 59.6284, 67.9643]]])


In [16]:
# Für GPU

# torch.cuda.memory_allocated()
# torch.cuda.memory_reserved()

In [17]:
m = torch.distributions.Binomial(30, .75)

x = m.sample((7, 15, 2))

print(x)

tensor([[[22., 24.],
         [19., 20.],
         [25., 27.],
         [18., 25.],
         [21., 19.],
         [22., 24.],
         [26., 23.],
         [23., 25.],
         [26., 23.],
         [18., 27.],
         [23., 20.],
         [23., 21.],
         [18., 21.],
         [18., 23.],
         [21., 23.]],

        [[26., 23.],
         [24., 24.],
         [24., 25.],
         [22., 19.],
         [24., 20.],
         [22., 22.],
         [23., 20.],
         [25., 24.],
         [18., 22.],
         [16., 22.],
         [18., 25.],
         [23., 23.],
         [24., 23.],
         [23., 24.],
         [21., 26.]],

        [[23., 23.],
         [17., 22.],
         [17., 27.],
         [21., 22.],
         [26., 22.],
         [19., 22.],
         [22., 22.],
         [23., 27.],
         [26., 19.],
         [22., 18.],
         [21., 24.],
         [23., 22.],
         [21., 22.],
         [24., 25.],
         [22., 20.]],

        [[19., 21.],
         [23., 22.],
       

In [19]:
avg = x.mean(1)
print(avg)

tensor([[21.5333, 23.0000],
        [22.2000, 22.8000],
        [21.8000, 22.4667],
        [22.3333, 21.2000],
        [23.8000, 21.8667],
        [21.6000, 22.2000],
        [22.5333, 22.0000]])


In [23]:
x_np = x.numpy()
x_avg_np = avg.numpy()

print(x_np)
print(x_avg_np)

[[[22. 24.]
  [19. 20.]
  [25. 27.]
  [18. 25.]
  [21. 19.]
  [22. 24.]
  [26. 23.]
  [23. 25.]
  [26. 23.]
  [18. 27.]
  [23. 20.]
  [23. 21.]
  [18. 21.]
  [18. 23.]
  [21. 23.]]

 [[26. 23.]
  [24. 24.]
  [24. 25.]
  [22. 19.]
  [24. 20.]
  [22. 22.]
  [23. 20.]
  [25. 24.]
  [18. 22.]
  [16. 22.]
  [18. 25.]
  [23. 23.]
  [24. 23.]
  [23. 24.]
  [21. 26.]]

 [[23. 23.]
  [17. 22.]
  [17. 27.]
  [21. 22.]
  [26. 22.]
  [19. 22.]
  [22. 22.]
  [23. 27.]
  [26. 19.]
  [22. 18.]
  [21. 24.]
  [23. 22.]
  [21. 22.]
  [24. 25.]
  [22. 20.]]

 [[19. 21.]
  [23. 22.]
  [21. 22.]
  [24. 21.]
  [25. 21.]
  [22. 26.]
  [23. 17.]
  [23. 22.]
  [20. 22.]
  [23. 22.]
  [21. 23.]
  [27. 21.]
  [22. 18.]
  [23. 20.]
  [19. 20.]]

 [[25. 21.]
  [22. 21.]
  [23. 16.]
  [24. 20.]
  [25. 24.]
  [25. 20.]
  [23. 25.]
  [24. 21.]
  [25. 23.]
  [27. 21.]
  [24. 23.]
  [20. 23.]
  [24. 23.]
  [24. 22.]
  [22. 25.]]

 [[21. 24.]
  [21. 25.]
  [24. 23.]
  [23. 23.]
  [23. 16.]
  [25. 24.]
  [23. 22.]
  [24.