In [5]:
import torch

a = torch.full((2, 3), 3)
b = torch.full((5, 1, 3), 3.)
print(a)
print(b)

tensor([[3, 3, 3],
        [3, 3, 3]])
tensor([[[3., 3., 3.]],

        [[3., 3., 3.]],

        [[3., 3., 3.]],

        [[3., 3., 3.]],

        [[3., 3., 3.]]])


In [6]:
c = a + b
print(c)
print(c.shape)

tensor([[[6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.]]])
torch.Size([5, 2, 3])


- (3, 1, 3), (2, 3, 3) --> no
• (4, 1), (3, 1, 1, 5) --> first becomes (1, 1, 4, 1) --> becomes (3, 1, 4, 5)
• (3), (3, 1, 1, 5) --> first becomes (1, 1, 1, 3) --> error (5!=3)
• (1, 4), (7, 1) --> (7, 4)
• (6, 3, 1, 7), (2, 7) --> second becomes (1, 1, 2, 7) --> (6, 3, 2, 7)
• (6, 3, 1, 7), (2, 1, 7) --> second becomes (1, 2, 1, 7) --> (6, ERROR) --> error
• (1, 2, 3, 1, 6), (8, 1, 3, 2, 6) --> (8, 2, 3, 2, 6)
• (2, 5, 1, 7), (9, 2, 3, 2, 1) --> first becomes (1, 2, 5, 1, 7) --> (9, 2, ERROR) --> error

In [9]:
import numpy as np
def add(a, b):
    return a[:, np.newaxis] + b

In [20]:
def add_with_unsqueeze(a, b):
    return a.unsqueeze(1) + b

In [21]:
a = torch.arange(5)
b = torch.arange(3)
print(add(a, b))
print(add_with_unsqueeze(a, b))

print(a.shape)
print(a.unsqueeze(1).shape)

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])
tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])
torch.Size([5])
torch.Size([5, 1])


In [22]:
def mult(a, b):
    return a.unsqueeze(3) * b.unsqueeze(1)

In [28]:
g = torch.Generator().manual_seed(42)
a = torch.rand((3, 2, 5), generator=g)
b = torch.rand((3, 5, 4), generator=g)

print(mult(a,b))

tensor([[[[8.3953e-01, 6.6405e-02, 7.8170e-01, 5.1455e-01],
          [3.0895e-01, 7.4022e-01, 5.2880e-01, 8.2715e-01],
          [2.1236e-01, 1.3106e-01, 2.4287e-01, 1.3952e-01],
          [6.8152e-01, 9.0790e-01, 7.5692e-01, 2.6996e-01],
          [3.0792e-01, 2.3015e-01, 2.9437e-01, 7.6234e-02]],

         [[5.7178e-01, 4.5227e-02, 5.3240e-01, 3.5045e-01],
          [8.6631e-02, 2.0756e-01, 1.4828e-01, 2.3194e-01],
          [4.4020e-01, 2.7167e-01, 5.0344e-01, 2.8921e-01],
          [6.6835e-01, 8.9036e-01, 7.4230e-01, 2.6475e-01],
          [1.0503e-01, 7.8508e-02, 1.0041e-01, 2.6004e-02]]],


        [[[4.7158e-03, 2.8675e-01, 1.0887e-01, 8.5074e-01],
          [3.8227e-01, 4.1972e-01, 3.9065e-01, 2.9163e-01],
          [7.7490e-01, 1.2584e-01, 4.6207e-01, 1.3800e-01],
          [3.7139e-01, 1.8610e-01, 3.7084e-01, 2.2472e-01],
          [6.7788e-01, 1.5092e-01, 1.4955e-01, 1.4954e-01]],

         [[2.1667e-03, 1.3175e-01, 5.0021e-02, 3.9087e-01],
          [5.7024e-01, 6.2610e-0